# Generated by Django 6.0.1 on 2026-01-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('achievement_type', models.CharField(choices=[('streak', 'Série'), ('lessons', 'Leçons'), ('exercises', 'Exercices'), ('quizzes', 'Quiz'), ('score', 'Score'), ('mastery', 'Maîtrise'), ('special', 'Spécial')], max_length=20, verbose_name='Type')),
                ('icon', models.CharField(max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#FFD700', max_length=7, verbose_name='Couleur')),
                ('requirement', models.PositiveIntegerField(default=1, verbose_name='Condition requise')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Badge de l'élève",
                'verbose_name_plural': 'Badges des élèves',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons_viewed', models.PositiveIntegerField(default=0, verbose_name='Leçons vues')),
                ('total_exercises_completed', models.PositiveIntegerField(default=0, verbose_name='Exercices complétés')),
                ('total_quizzes_completed', models.PositiveIntegerField(default=0, verbose_name='Quiz complétés')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Points totaux')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Série actuelle (jours)')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Plus longue série')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('weekly_goal', models.PositiveIntegerField(default=5, verbose_name='Objectif hebdomadaire (leçons)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Progression de l'élève",
                'verbose_name_plural': 'Progressions des élèves',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('exercises_completed', models.PositiveIntegerField(default=0, verbose_name='Exercices complétés')),
            ],
            options={
                'verbose_name': "Session d'étude",
                'verbose_name_plural': "Sessions d'étude",
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.PositiveIntegerField(default=0, verbose_name='Leçons complétées')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='Total des leçons')),
                ('exercises_completed', models.PositiveIntegerField(default=0, verbose_name='Exercices complétés')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Score moyen')),
                ('mastery_level', models.PositiveIntegerField(default=1, verbose_name='Niveau de maîtrise')),
            ],
            options={
                'verbose_name': 'Progression par matière',
                'verbose_name_plural': 'Progressions par matière',
            },
        ),
        migrations.CreateModel(
            name='WeakArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concept')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'erreurs")),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Zone faible',
                'verbose_name_plural': 'Zones faibles',
                'ordering': ['-error_count'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('sixieme', '6ème'), ('cinquieme', '5ème'), ('quatrieme', '4ème'), ('troisieme', '3ème'), ('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('prerequisites', models.ManyToManyField(blank=True, to='progress.skill', verbose_name='Prérequis')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lessons.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, 'Non commencé'), (1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Expert')], default=0, verbose_name='Niveau de maîtrise')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('successes', models.PositiveIntegerField(default=0, verbose_name='Succès')),
                ('last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Dernière tentative')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='progress.skill', verbose_name='Compétence')),
            ],
            options={
                'verbose_name': 'Maîtrise de compétence',
                'verbose_name_plural': 'Maîtrises de compétences',
            },
        ),
    ]
