# Generated by Django 6.0.1 on 2026-01-28 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0003_initial'),
        ('lessons', '0002_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='progress.achievement', verbose_name='Badge'),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='lessons_viewed',
            field=models.ManyToManyField(blank=True, to='lessons.lesson', verbose_name='Leçons vues'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.subject', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='subjectprogress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lessons.subject', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='weakarea',
            name='recommended_exercises',
            field=models.ManyToManyField(blank=True, to='exercises.exercise', verbose_name='Exercices recommandés'),
        ),
        migrations.AddField(
            model_name='weakarea',
            name='recommended_lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson', verbose_name='Leçons recommandées'),
        ),
        migrations.AddField(
            model_name='weakarea',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='weakarea',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak_areas', to='lessons.subject', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='skillmastery',
            unique_together={('student', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='studentachievement',
            unique_together={('student', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectprogress',
            unique_together={('student', 'subject')},
        ),
    ]
