# Generated by Django 4.2.28 on 2026-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Matière enseignée'),
        ),
    ]
