# Generated by Django 6.0.1 on 2026-01-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exercise_type', models.CharField(choices=[('qcm', 'QCM'), ('text', 'Réponse texte'), ('number', 'Réponse numérique'), ('matching', 'Association'), ('fill_blank', 'Remplir les blancs'), ('ordering', 'Ordonnancement')], default='qcm', max_length=20, verbose_name="Type d'exercice")),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=20, verbose_name='Difficulté')),
                ('level', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('sixieme', '6ème'), ('cinquieme', '5ème'), ('quatrieme', '4ème'), ('troisieme', '3ème'), ('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('content', models.JSONField(verbose_name='Contenu (JSON)')),
                ('correct_answers', models.JSONField(verbose_name='Réponses correctes')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('hints', models.JSONField(blank=True, default=list, verbose_name='Indices')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='Points')),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de temps (secondes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['order', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(verbose_name='Réponse donnée')),
                ('is_correct', models.BooleanField(verbose_name='Correct')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('hints_used', models.PositiveIntegerField(default=0, verbose_name='Indices utilisés')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Numéro de tentative')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Tentative d'exercice",
                'verbose_name_plural': "Tentatives d'exercices",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('sixieme', '6ème'), ('cinquieme', '5ème'), ('quatrieme', '4ème'), ('troisieme', '3ème'), ('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de temps totale (minutes)')),
                ('passing_score', models.PositiveIntegerField(default=50, verbose_name='Score de réussite (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Score total')),
                ('percentage', models.PositiveIntegerField(default=0, verbose_name='Pourcentage')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Temps passé (secondes)')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-started_at'],
            },
        ),
    ]
