# Generated by Django 6.0.1 on 2026-01-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.lesson', verbose_name='Leçon'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='lessons.subject', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='exerciseattempt',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise', verbose_name='Exercice'),
        ),
    ]
