# Generated by Django 4.2.28 on 2026-02-18 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Généré par IA'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('qcm', 'QCM'), ('classic', "Classique (Fiche d'exercices)")], default='qcm', max_length=20, verbose_name="Type d'exercice"),
        ),
    ]
