# Generated by Django 4.2.28 on 2026-02-22 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_creator_exercise_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('other', 'Autre')], default='pdf', max_length=20, verbose_name='Type')),
                ('file', models.FileField(upload_to='exercise_resources/', verbose_name='Fichier')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='exercises.exercise', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': "Ressource d'exercice",
                'verbose_name_plural': "Ressources d'exercices",
                'ordering': ['order'],
            },
        ),
    ]
