# Generated by Django 6.0.1 on 2026-01-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField()),
                ('content', models.TextField(verbose_name='Contenu')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('level', models.CharField(choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('sixieme', '6ème'), ('cinquieme', '5ème'), ('quatrieme', '4ème'), ('troisieme', '3ème'), ('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_official', models.BooleanField(default=True, verbose_name='Programme officiel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, verbose_name='URL Vidéo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Vidéo'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'Lien'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_resources/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completion_percentage', models.PositiveIntegerField(default=0, verbose_name='Pourcentage de complétion')),
            ],
            options={
                'verbose_name': 'Vue de leçon',
                'verbose_name_plural': 'Vues de leçons',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['order', 'name'],
            },
        ),
    ]
