# Generated by Django 6.0.1 on 2026-01-28 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.chapter', verbose_name='Chapitre'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lessons.lesson', verbose_name='Leçon'),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lessons.lesson', verbose_name='Leçon'),
        ),
        migrations.AddField(
            model_name='lessonview',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_views', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lessons.subject', verbose_name='Matière'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonview',
            unique_together={('lesson', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'slug')},
        ),
    ]
