# Generated by Django 4.2.28 on 2026-02-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['level', 'order', 'title'], 'verbose_name': 'Leçon', 'verbose_name_plural': 'Leçons'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_content',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='Contenu PDF'),
        ),
    ]
